var api_transformation = {
	"Book of Mormon": {
		abbr: "bofm",
		total_pages: 531,
		books: {
			"Title Page": "title-page",
			"Book of Mormon Title Page": "bofm-title",
			"Introduction": "introduction",
			"Testimony of the Three Witnesses": "three",
			"Testimony of the Eight Witnesses": "eight",
			"Testimony of Joseph Smith": "js",
			"Explanation": "explanation",
			"1 Nephi": "1-ne",
			"2 Nephi": "2-ne",
			"Jacob": "jacob",
			"Enos": "enos",
			"Jarom": "jarom",
			"Omni": "omni",
			"Words of Mormon": "w-of-m",
			"Mosiah": "mosiah",
			"Alma": "alma",
			"Helaman": "hel",
			"3 Nephi": "3-ne",
			"4 Nephi": "4-ne",
			"Mormon": "morm",
			"Ether": "ether",
			"Moroni": "moro",
		},
		pages: {
			"Title Page": 1,
			"Book of Mormon Title Page": 1,
			"Introduction": 1,
			"Testimony of the Three Witnesses": 1,
			"Testimony of the Eight Witnesses": 2,
			"Testimony of Joseph Smith": 4,
			"Explanation": 1,
			"1 Nephi": 53,
			"2 Nephi": 64,
			"Jacob": 19,
			"Enos": 3,
			"Jarom": 3,
			"Omni": 2,
			"Words of Mormon": 2,
			"Mosiah": 62,
			"Alma": 161,
			"Helaman": 38,
			"3 Nephi": 59,
			"4 Nephi": 4,
			"Mormon": 18,
			"Ether": 31,
			"Moroni": 13,
		}
	},
	"Doctrine and Covenants": {
		abbr: "dc-testament",
		total_pages: 294,
		books: {
			"D&C": "dc"
		},
		pages: {
			"D&C": 294
		},
	},
	"Pearl of Great Price": {
		abbr: "pgp",
		total_pages: 61,
		books: {
			"Moses": "moses",
			"Abraham": "abr",
			"Joseph Smith-Matthew": "js-m",
			"Joseph Smith-History": "js-h",
			"Articles of Faith": "a-of-f",
		},
		pages: {
			"Moses": 27,
			"Abraham": 13,
			"Joseph Smith-Matthew": 3,
			"Joseph Smith-History": 12,
			"Articles of Faith": 2,
		}
	},
	"New Testament": {
		abbr: "nt",
		total_pages: 1,
		books: {
			"Matthew": "matt",
			"Mark": "mark",
			"Luke": "luke",
			"John": "john",
			"Acts": "acts",
			"Romans": "rom",
			"1 Corinthians": "1-cor",
			"2 Corinthians": "2-cor",
			"Galatians": "gal",
			"Ephesians": "eph",
			"Philipians": "philip",
			"Colossians": "col",
			"1 Thessalonians": "1-thes",
			"2 Thessalonians": "2-thes",
			"1 Timothy": "1-tim",
			"2 Timothy": "2-tim",
			"Titus": "titus",
			"Philemon": "philem",
			"Hebrews": "heb",
			"James": "james",
			"1 Peter": "1-pet",
			"2 Peter": "2-pet",
			"1 John": "1-jn",
			"2 John": "2-jn",
			"3 John": "3-jn",
			"Jude": "jude",
			"Revelation": "rev",
		},
		pages: {
			"Matthew": 1,
			"Mark": 1,
			"Luke": 1,
			"John": 1,
			"Acts": 1,
			"Romans": 1,
			"1 Corinthians": 1,
			"2 Corinthians": 1,
			"Galatians": 1,
			"Ephesians": 1,
			"Philipians": 1,
			"Colossians": 1,
			"1 Thessalonians": 1,
			"2 Thessalonians": 1,
			"1 Timothy": 1,
			"2 Timothy": 1,
			"Titus": 1,
			"Philemon": 1,
			"Hebrews": 1,
			"James": 1,
			"1 Peter": 1,
			"2 Peter": 1,
			"1 John": 1,
			"2 John": 1,
			"3 John": 1,
			"Jude": 1,
			"Revelation": 1,
		}
	},
	"Old Testament": {
		abbr: "ot",
		total_pages: 1,
		books: {
			"Genesis": "gen",
			"Exodus": "ex",
			"Numbers": "num",
			"Leviticus": "lev",
			"Deuteronomy": "deut",
			"Joshua": "josh",
			"Judges": "judg",
			"Ruth": "ruth",
			"1 Samuel": "1-sam",
			"2 Samuel": "2-sam",
			"1 Kings": "1-kgs",
			"2 Kings": "2-kgs",
			"1 Chronicles": "1-chr",
			"2 Chronicles": "2-chr",
			"Ezra": "ezra",
			"Nehemiah": "neh",
			"Esther": "esth",
			"Job": "job",
			"Psalms": "ps",
			"Proverbs": "prov",
			"Ecclesiastes": "eccl",
			"Song of Solomon": "song",
			"Isiah": "isa",
			"Jeremiah": "jer",
			"Lamentations": "lam",
			"Ezekiel": "ezek",
			"Daniel": "dan",
			"Hosea": "hosea",
			"Joel": "joel",
			"Amos": "amos",
			"Obadiah": "obad",
			"Jonah": "jonah",
			"Micah": "micah",
			"Nahum": "nahum",
			"Habakkuk": "hab",
			"Zephaniah": "zeph",
			"Haggai": "hag",
			"Zechariah": "zech",
			"Malachi": "mal",
		},
		pages: {
			"Genesis": 1,
			"Exodus": 1,
			"Numbers": 1,
			"Leviticus": 1,
			"Deuteronomy": 1,
			"Joshua": 1,
			"Judges": 1,
			"Ruth": 1,
			"1 Samuel": 1,
			"2 Samuel": 1,
			"1 Kings": 1,
			"2 Kings": 1,
			"1 Chronicles": 1,
			"2 Chronicles": 1,
			"Ezra": 1,
			"Nehemiah": 1,
			"Esther": 1,
			"Job": 1,
			"Psalms": 1,
			"Proverbs": 1,
			"Ecclesiastes": 1,
			"Song of Solomon": 1,
			"Isiah": 1,
			"Jeremiah": 1,
			"Lamentations": 1,
			"Ezekiel": 1,
			"Daniel": 1,
			"Hosea": 1,
			"Joel": 1,
			"Amos": 1,
			"Obadiah": 1,
			"Jonah": 1,
			"Micah": 1,
			"Nahum": 1,
			"Habakkuk": 1,
			"Zephaniah": 1,
			"Haggai": 1,
			"Zechariah": 1,
			"Malachi": 1,
		}
	}
};